In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import requests
from bs4 import BeautifulSoup
import pickle
import ast,requests,json

In [2]:
df = pd.read_csv('tmdb.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9480 entries, 0 to 9479
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    9480 non-null   int64
 1   id            9480 non-null   int64
 2   title         9480 non-null   object
 3   overview      9464 non-null   object
 4   popularity    9480 non-null   float64
 5   vote_average  9480 non-null   float64
 6   vote_count    9480 non-null   int64
 7   release_date  9480 non-null   object
 8   keywords      9480 non-null   object
 9   genres        9480 non-null   object
 10  cast          9480 non-null   object
 11  crew          9480 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 888.9+ KB

In [3]:
movies = df[['id','title','overview','genres','keywords','cast','crew']]

In [4]:
movies_copy= movies.copy()
movies.dropna(inplace=True)

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12268\3219022593.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [5]:
movies_copy['genres'][9477].replace("'",'').replace(" ",'').strip('[]')

'Thriller,Crime,ScienceFiction,Mystery'

In [6]:
movies_copy

,id,title,overview,genres,keywords,cast,crew
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","['Comedy', 'Drama', 'Romance']",[],"['Shah Rukh Khan', 'Kajol', 'Amrish Puri', 'An...",['Aditya Chopra']
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"['Drama', 'Crime']","['prison', 'corruption', 'police brutality', '...","['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'...",['Frank Darabont']
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']","['italy', 'loss of loved one', 'love at first ...","['Marlon Brando', 'Al Pacino', 'James Caan', '...",['Francis Ford Coppola']
3,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,['Romance'],['based on novel or book'],"['Melanie Zanetti', 'Giulio Berruti', 'James A...",['Tosca Musk']
4,424,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']","['based on novel or book', 'factory', 'concent...","['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes...",['Steven Spielberg']
...,...,...,...,...,...,...,...
9475,21435,French Fried Vacation 3,"After the Club Med and skiing, what happened t...",['Comedy'],"['holiday', 'sardinia, italy', 'sequel', 'reun...","['Josiane Balasko', 'Michel Blanc', 'Marie-Ann...",['Patrice Leconte']
9476,17711,The Adventures of Rocky & Bullwinkle,Rocky and Bullwinkle have been living off the ...,"['Family', 'Adventure', 'Animation', 'Comedy',...","['helicopter', 'police', 'cartoon', 'road trip...","['Rene Russo', 'Jason Alexander', 'Piper Perab...",['Des McAnuff']
9477,17532,S. Darko,"S. Darko follows Samantha Darko, the younger s...","['Thriller', 'Crime', 'Science Fiction', 'Myst...","['sequel', 'stranded', 'end of the world', 'sh...","['Daveigh Chase', 'Elizabeth Berkley', 'Briana...",['Chris Fisher']
9478,13908,The Master of Disguise,A sweet-natured Italian waiter named Pistachio...,"['Comedy', 'Family']","['disguise', 'aftercreditsstinger', 'duringcre...","['Dana Carvey', 'Brent Spiner', 'Jennifer Espo...",['Perry Andelin Blake']
9479,580,Jaws: The Revenge,"After another deadly shark attack, Ellen Brody...","['Adventure', 'Thriller', 'Horror']","['shark attack', 'bahamas', 'dying and death',...","['Lorraine Gary', 'Lance Guest', 'Mario Van Pe...",['Joseph Sargent']

In [8]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [9]:
movies_copy['genres'] = movies_copy['genres'].apply(convert)
movies_copy.head()

TypeError: string indices must be integers

In [8]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\2480151099.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(convert)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [10]:
movies['cast'] = movies['cast'].apply(convert3)

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\872951896.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(convert3)

In [11]:
df['cast']=movies['cast']

In [12]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [13]:
movies['crew'] = movies['crew'].apply(fetch_director)

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\4159008703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(fetch_director)

In [14]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [15]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\3118682489.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(collapse)
C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\3118682489.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(collapse)
C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\3118682489.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(collapse)
C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\3118682489.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(collapse)

In [16]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]"

In [17]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\1645461255.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [18]:
movies['overview']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [19]:
movies['tags']= movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

C:\Users\Scott Fernandes\AppData\Local\Temp\ipykernel_12220\1684007356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']= movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [20]:
new_movies = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [21]:
new_movies['tags']=new_movies['tags'].apply(lambda x:" ".join(x))

In [22]:
new_movies

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [23]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(txt):
    L=[]
    
    for i in txt.split():
        L.append(ps.stem(i))

    return " ".join(L)

In [24]:
new_movies['tags']=new_movies['tags'].apply(stem)

In [25]:
new_movies

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [27]:
vectors = cv.fit_transform(new_movies['tags']).toarray()

In [28]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
similarity = cosine_similarity(vectors)

In [30]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x:x[1])[1:12]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.2503866978335957),
 (582, 0.24511108480187255),
 (1204, 0.24455799402225925),
 (1194, 0.23179316248638274),
 (778, 0.23174488732966075),
 (4048, 0.2278389747471728),
 (1920, 0.22528177844479153)]

In [31]:
def get_trailer(movie_id):
    response = requests.get('http://api.themoviedb.org/3/movie/{}?api_key=75d6f4d358afd80023fc135735da8af5&append_to_response=videos'.format(movie_id))
    data = response.json()
    key = data['videos']['results']
    return key

In [48]:
def get_castcrew(movie_id):
    response = requests.get('http://api.themoviedb.org/3/movie/{}?api_key=75d6f4d358afd80023fc135735da8af5&append_to_response=credits'.format(movie_id))
    data = response.json()
    dets =  data['credits']['cast'][0:10]
    ids = [i['id'] for i in dets]
    details= []
    character = [i['character'] for i in dets]
    poster = [i['profile_path'] for i in dets]
    for i in ids:
        response2 = requests.get('https://api.themoviedb.org/3/person/{}?api_key=75d6f4d358afd80023fc135735da8af5'.format(i))
        data2 = response2.json()
        details.append(data2)
    name = [i['name'] for i in details]
    bio = [i['biography'] for i in details]
    place = [i['place_of_birth'] for i in details]
    bday = [i['birthday'] for i in details]
    moviesss= []
    mv = (movies.loc[movies['cast']=='Tobey Maguire']).to_string(header=False,index=False,columns=['title'])
    moviesss.append(mv)
    posters =[]
    for i in poster:
        posters.append("https://image.tmdb.org/t/p/original"+i)
    detailjson = {"name":name,"poster":poster,"character":character,"Biography":bio,"Birthplace":place,"bday":bday}
    
    return movies

In [33]:
def fetch_poster(movie_id):
    response= requests.get('https://api.themoviedb.org/3/movie/{}?api_key=75d6f4d358afd80023fc135735da8af5&language=en-US'.format(movie_id))
    data = response.json()
    path = 'https://image.tmdb.org/t/p/w500'+data['poster_path']
    return path

In [34]:
def backdrop_poster(movie_id):
    response= requests.get('https://api.themoviedb.org/3/movie/{}?api_key=75d6f4d358afd80023fc135735da8af5&language=en-US'.format(movie_id))
    data = response.json()
    path =  "https://image.tmdb.org/t/p/w1280"+data['backdrop_path']
    return path

In [35]:
def get_movie_details(movie):
    genre = (movies.loc[movies['title']==movie]).to_string(header=False,index=False,columns=['genres'])
    overview = (movies.loc[movies['title']==movie]).to_string(header=False,index=False,columns=['overview']).replace(",","")
    overview  = overview.strip('[]')
    status = (df.loc[df['title']==movie]).to_string(header=False,index=False,columns=['release_date'])
    genre = genre.strip('[]')
    genre = genre.split(',')
    genres = []
    for i in genre:
        genres.append(i)
        
    return genres,overview,status

In [38]:
def recommend(movie):
    movie_index = new_movies[new_movies['title']==movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:12]
    titles= []
    ip_id = (new_movies.loc[new_movies['title']==movie]).to_string(header=False,index=False,columns=['movie_id'])
    posters =[fetch_poster(ip_id)]
    details = get_movie_details(movie)
    backdrop = backdrop_poster(ip_id)
    trailer  = get_trailer(ip_id)
    creds = get_castcrew(ip_id)
    for i in movie_list:
        title = new_movies.iloc[i[0]].title
        movie_id = new_movies.iloc[i[0]].movie_id
        titles.append(title)
        posters.append(fetch_poster(movie_id))

    return titles

In [49]:
recommend('Spider-Man 3')

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]","[Ever, since, the, second, grade, when, he, fi..."